### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by moshetanzer** [pmanikas/vue-guitar-tuner#1]
Hi,

I really like your project.

First of all there is an aphostreohe missing from the code example in your docs;
`  <VueGuitarTuner :display-note="false" :displayGrid="false" :tunerClasses="['tuner**'**, 'tunerArea']"/>`.
Second of all would really appreciate if you could help me implement this into my project, for some reason I just get a white screen when serving it.

Best Regards

**Comment by pmanikas** [comment]
Hello @goldbergmoshe , thanks. 

Can you send me your code so I can check? Also which version of vue.js are you using?

**Comment by moshetanzer** [comment]
Hi,

Thank you so much for getting back to me!

Here is my code;


<template>
    <VueGuitarTuner :display-note="false" :displayGrid="false" :tunerClasses="['tuner', 'tunerArea']"/>
</template>

<script>
import VueGuitarTuner from 'vue-guitar-tuner';
import("vue-guitar-tuner/dist/vue-guitar-tuner.css");
export default {
    components: {
    VueGuitarTuner,
  },
    data() {
        return {
            isTunerActive: false,
            data: {},
        };
    },
    methods: {
        statusUpdate(status) {
            this.isTunerActive = status;
        },
        dataUpdate(data) {
            this.data = data;
        },
    },
}
</script>

<style>

</style>


I installed the package with NPM.


Really appreciate it!

Best Regards

**Comment by pmanikas** [comment]
@goldbergmoshe can you please try to implement it similarly to my demo example [here](https://github.com/pmanikas/vue-tone-generator-demo)

Plugin's functionality is working out of the box but you have to take care of the container and the activation button in terms of html and css structure. You can find everything inside the demo above.

**Comment by moshetanzer** [comment]
Hi,

Sorry to drive you crazy!

Tried not managing to import the correct files…



Would really appreciate if you could help me out!

Best Regards

**Comment by pmanikas** [comment]
You can share your repo with all of your code and I can give you a quick review!

**Comment by moshetanzer** [comment]
Hi,

Thank you so much.

It was local, so just put it on stackblitz.


https://stackblitz.com/edit/vue-eeqemb?file=src/components/HelloWorld.vue <https://stackblitz.com/edit/vue-eeqemb?file=src/components/HelloWorld.vue>

Hope that is ok!

Really appreciate it!

Best Regards

**Comment by pmanikas** [comment]
@goldbergmoshe it's most possibly because you're using vue 3. You can give it a try with latest version of vue 2. If that's the case, let me know so we can close this issue and open a new one for vue 3 support. Here's an example on stackblitz with vue 2.

https://stackblitz.com/edit/vue2-vue-cli-3czdyq?file=src%2FApp.vue
